spring:
  datasource:
    url: 'jdbc:h2:mem:testdb;MODE=Oracle'
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %5p [%logger{0}] %m%n"
  level:
    root: info
    com.inomera: info

config-manager:
  enabled: true
  source: jdbc
  reload:
    enabled: true
    trigger: periodical
    period: 30
    period-unit: seconds
  jdbc:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:testdb;MODE=Oracle;NON_KEYWORDS=VALUE,KEY'
    username: sa
    password: password
    select-sql: SELECT KEY, VALUE FROM APP_SETTINGS where APPLICATION = 'charging'
  encryption:
    enabled: true
    secret-key: '6374ca4b80c0bfc051cfd9dd6d8d3e9e'
