config-manager:
  enabled: true
  auto-reload: true
  reload-trigger: periodical
  reload-period-in-milliseconds: 60000
  cassandra:
    nodes:
      - host: localhost
        port: 9042
    username: cassandra
    password: cassandra
    sql:
      select: select key, value from example_cassandra.app_settings where application = 'application'
