config-manager:
  enabled: true
  source: cassandra
  reload:
    enabled: true
    trigger: periodical
    period: 5
    period-unit: seconds
  cassandra:
    nodes:
      - host: localhost
        port: 9042
    username: cassandra
    password: cassandra
    select-sql: select key, value from example_cassandra.app_settings where application = 'application'
    local-datacenter: datacenter1
