config-manager:
  enabled: true
  source: mongo
  reload:
    enabled: true
    trigger: periodical
    period: 5
    period-unit: seconds
  mongo:
    servers:
      - host: 127.0.0.1
        port: 27017
    query:
      application: application
      label: master
      profile: default
    db-name: testDB
    value-field-name: value
    key-field-name: key
    collection: testCollection


